name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
env:
  IMAGE_NAME: anime-life-nextjs
  COPY_TO_ACR: true
jobs:
  prepare-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.prepare_version.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read json
        id: read_json
        run: |
          echo "packageJson<<EOF" >> $GITHUB_OUTPUT
          cat ./package.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Prepare version
        id: prepare_version
        run: |
          tag=`echo "${{fromJson(steps.read_json.outputs.packageJson).version}}"`-${{ github.sha }}
          [[ "${{ github.ref }}" == "refs/heads/main" ]] && tag=`echo "${{fromJson(steps.read_json.outputs.packageJson).version}}"`
          echo tag=$tag
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
  docker-build:
    needs: [prepare-version]
    runs-on: ubuntu-latest
    outputs:
      image_id: ${{ steps.push_image.outputs.image_id }}
    env:
      IMAGE_TAG: ${{ needs.prepare-version.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        id: push_image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          echo IMAGE_TAG=$IMAGE_TAG
          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_TAG
          docker push $IMAGE_ID:$IMAGE_TAG
          echo "image_id=$IMAGE_ID" >> "$GITHUB_OUTPUT"
  docker-copy:
    runs-on: ubuntu-latest
    needs: [prepare-version, docker-build]
    outputs:
      image_id: ${{ steps.export_image_id.outputs.image_id }}
    env:
      IMAGE_ID: ${{ needs.docker-build.outputs.image_id }}
      IMAGE_TAG: ${{ needs.prepare-version.outputs.tag }}
    steps:
      - name: Download from GitHub Packages
        run: |
          echo "pulling $IMAGE_ID:$IMAGE_TAG"
          docker pull $IMAGE_ID:$IMAGE_TAG
      - name: Login to ACR
        if: ${{ env.COPY_TO_ACR == 'true' }}
        uses: aliyun/acr-login@v1
        with:
          login-server: 'https://registry.cn-shanghai.aliyuncs.com'
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}
      - name: Push to ACR
        id: push_acr
        if: ${{ env.COPY_TO_ACR == 'true' }}
        run: |
          ACR_IMAGE_ID=registry.cn-shanghai.aliyuncs.com/animelife/$IMAGE_NAME
          docker tag $IMAGE_ID:$IMAGE_TAG $ACR_IMAGE_ID:$IMAGE_TAG
          docker push $ACR_IMAGE_ID:$IMAGE_TAG
          echo "acr_image_id=$ACR_IMAGE_ID" >> "$GITHUB_OUTPUT"
      - name: Export image id
        id: export_image_id
        env:
          ACR_IMAGE_ID: ${{ steps.push_acr.outputs.acr_image_id }}
        run: |
          image_id=$IMAGE_ID
          echo "Origin IMAGE_ID=$IMAGE_ID"
          [[ "${{ env.COPY_TO_ACR }}" == 'true' ]] && image_id=$ACR_IMAGE_ID
          echo "Final IMAGE_ID=$image_id"
          echo "image_id=$image_id" >> "$GITHUB_OUTPUT"
  publish-helm:
    runs-on: ubuntu-latest
    needs: [prepare-version, docker-build, docker-copy]
    env:
      IMAGE_ID: ${{ needs.docker-copy.outputs.image_id }}
      IMAGE_TAG: ${{ needs.prepare-version.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout helm-charts repo
        uses: actions/checkout@v4
        with:
          repository: HatsuneMK00/helm-charts
          path: helm-charts
          token: ${{ secrets.GH_TOKEN }}
      - name: Update image tag
        run: |
          ENCODED_IMAGE_ID=$(echo ${{ env.IMAGE_ID }} | sed 's/\//\\\//g')
          sed -i "s/repository:.*/repository: $ENCODED_IMAGE_ID/" .ci/charts/anime-life-nextjs/values.yaml
          sed -i "s/tag:.*/tag: ${{ env.IMAGE_TAG }}/" .ci/charts/anime-life-nextjs/values.yaml
      - name: Read current chart version
        uses: mikefarah/yq@master
        id: read_chart_version
        with:
          cmd: yq '.version' helm-charts/charts/anime-life-nextjs/Chart.yaml
      - name: Update chart version
        id: update_chart_version
        run: |
          version=${{ steps.read_chart_version.outputs.result }}
          echo "current chart version: $version"
          new_version=$(.github/scripts/incre_semver.sh $version patch)
          echo "new chart version: $new_version"
          CHART_VERSION=$(echo $version | cut -d '-' -f1)-${{ github.sha }}
          [[ "${{ github.ref }}" == "refs/heads/main" ]] && CHART_VERSION=$new_version
          sed -i "s/version:.*/version: $CHART_VERSION/" .ci/charts/anime-life-nextjs/Chart.yaml
          echo "chart_version=$CHART_VERSION" >> "$GITHUB_OUTPUT"
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.12.2' # default is latest (stable)
      - name: Setup KUBE_CONFIG
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Deploy to k3s
        run: |
          helm upgrade --wait --timeout 5m --namespace default anime-life-nextjs .ci/charts/anime-life-nextjs
      - name: Commit and push changes to HatsuneMK00/helm-charts
        run: |
          cp -r .ci/charts/anime-life-nextjs helm-charts/charts
          cd helm-charts
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Update anime-life-nextjs to ${{ steps.update_chart_version.outputs.chart_version }}"
          git push
      - name: Summary
        run: |
          echo "Helm Chart Version: ${{ steps.update_chart_version.outputs.chart_version }}" >> $GITHUB_STEP_SUMMARY