on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  IMAGE_TAG: ${{ github.sha }}
permissions:
  contents: write
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kmakise556/anime-life-nextjs:${{ env.IMAGE_TAG }}
  deploy-helm:
    runs-on: ubuntu-latest
    needs: [docker-build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout helm-charts repo
        uses: actions/checkout@v4
        with:
          repository: HatsuneMK00/helm-charts
          path: helm-charts
      - name: debug
        run: |
          pwd
          ls ${{ github.workspace }}/helm-charts
          ls ${{ github.workspace }}/helm-charts/charts
          ls ${{ github.workspace }}/helm-charts/charts/anime-life-nextjs
      - name: Update image tag
        run: |
          sed -i "s/tag:.*/tag: ${{ env.IMAGE_TAG }}/" ${{ github.workspace }}/helm-charts/charts/anime-life-nextjs/values.yaml
      - name: Update chart version
        run: |
          sed -i "s/version:.*/version: ${{ env.IMAGE_TAG }}/" ${{ github.workspace }}/helm-charts/charts/anime-life-nextjs/Chart.yaml
      - name: Commit and push changes to HatsuneMK00/helm-charts
        run: |
          cd ${{ github.workspace }}/helm-charts
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Update anime-life-nextjs to ${{ env.IMAGE_TAG }}"
          git remote set-url origin https://HatsuneMK00:${{ secrets.TOKEN }}@github.com/HatsuneMK00/helm-charts.git
          git push