on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  prepare-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.prepare_version.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read json
        id: read_json
        run: |
          echo "packageJson<<EOF" >> $GITHUB_OUTPUT
          cat ./package.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Prepare version
        id: prepare_version
        run: |
          tag=`echo "${{fromJson(steps.read_json.outputs.packageJson).version}}"`-${{ github.sha }}
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
  docker-build:
    needs: [prepare-version]
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ needs.prepare-version.outputs.tag }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: kmakise556/anime-life-nextjs:${{ env.IMAGE_TAG }}
  deploy-helm:
    runs-on: ubuntu-latest
    needs: [prepare-version, docker-build]
    if: github.ref == 'refs/heads/main'
    env:
      IMAGE_TAG: ${{ needs.prepare-version.outputs.tag }}
    steps:
      - name: Checkout helm-charts repo
        uses: actions/checkout@v4
        with:
          repository: HatsuneMK00/helm-charts
          path: helm-charts
          token: ${{ secrets.GH_TOKEN }}
      - name: debug
        run: |
          pwd
          ls ${{ github.workspace }}/helm-charts
          ls ${{ github.workspace }}/helm-charts/charts
          ls ${{ github.workspace }}/helm-charts/charts/anime-life-nextjs
      - name: Update image tag
        run: |
          sed -i "s/tag:.*/tag: ${{ env.IMAGE_TAG }}/" ${{ github.workspace }}/helm-charts/charts/anime-life-nextjs/values.yaml
      - name: Update chart version
        run: |
          sed -i "s/version:.*/version: ${{ env.IMAGE_TAG }}/" ${{ github.workspace }}/helm-charts/charts/anime-life-nextjs/Chart.yaml
      - name: Commit and push changes to HatsuneMK00/helm-charts
        run: |
          cd ${{ github.workspace }}/helm-charts
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Update anime-life-nextjs to ${{ env.IMAGE_TAG }}"
          git push